source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

# Specify your gem's dependencies in vue_r.gemspec.

gem "vue_r" , path: "../"

gem "rails"

gem "puma"  , "5.6.5"
gem "haml-rails"
gem "sqlite3"
gem "active_hash"

gem "opal-rails"
gem 'opal-optimizer', git: "https://github.com/hmdne/opal-optimizer" , require: false
gem "terser"
